name: Running an action

on:
  push:
    branches: [main]
    
jobs:
  build:
  
    runs-on: windows-latest
    
    steps:
      - name: Set current date
        uses: 1466587594/get-current-time@v2
        id: current-time
        
      - name: test format() over multiline
        env:
          VERSION: |
            '${{ steps.current-time.outputs.year}}.
            ${{ steps.current-time.outputs.month }}.
            ${{ steps.current-time.outputs.day }}.
            ${env:GITHUB_RUN_NUMBER}'
        run: |
          echo  ${env:VERSION}
