name: Running an action

on:
  push:
    branches: [main]
    
jobs:
  build:
  
    runs-on: windows-latest
    
    steps:
      - name: Set current date
        uses: 1466587594/get-current-time@v2
        id: current-time
        
      - name: Set Version env var
        id: set-version
        env: 
          version: "${{ steps.current-time.outputs.year }}.\
          ${{ steps.current-time.outputs.month }}.\
          ${{ steps.current-time.outputs.day }}.\
          ${{ github.run_number }}"
        run: |
          echo "setting version environment variable..."
          echo "::set-output name=current::$version"
        
      - name: Use Version env ver
        run: |
          echo ${{ steps.set-version.current }}
          echo  '${{ env.version }}'
          
