name: Running an action

on:
  push:
    branches: [main]
    
jobs:
  build:
  
    runs-on: windows-latest
    
    steps:
      - name: Set current date
        uses: 1466587594/get-current-time@v2
        id: current-time
        
      - name: test format() over multiline
        env:
          YEAR: ${{ steps.current-time.outputs.year }}
          MONTH: ${{ steps.current-time.outputs.month }}
          DAY: ${{ steps.current-time.outputs.day }}
          RN: ${{ github.run_number }}
          VERSION: ${{ format('{0}.{1}.{2}.{3}', ${{env.YEAR}}, $MONTH, $DAY, $RN) }}
        run: |
          echo  ${env:VERSION}
